#!/bin/bash
set -e

# the order is important because some of them rely on others
#
# once these docker files settle down the whole thing can be repository based
# but I got sick of re-uploading large images because inevitably the numpty that
# I am gets it wrong at each and every turn - much like this 3 line comment that
# a) has said not a lot and
# b) has now become 5 lines
images=( hipache mongo redis node digger )

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

function install_image {
	# we dont log output for the hipache container cos it breaks waiting for wget
	#flags=" -q"
	flags=""
	echo "building image $1"
	docker rmi `docker images | grep quarry/$1 | awk '{print $3}'`
	docker build $flags -t quarry/$1 dockerfiles/$1
}

case "$1" in
  all)
		# check for the install folder otherwise clone & build
		for IMAGE in "${images[@]}"
		do
		  install_image $IMAGE
		done
		;;

	*)
		if [ -z $1 ]; then
			echo "Please specifiy a file to build" 1>&2
   		exit 1
		fi
		install_image $1
		;;
esac

